Feature/last input ingredients
YAPP-19th/Android-Team-2-Frontend pull request #36
Opened 2021-12-07 19:06 UTC by ashwon12

## 무슨 기능인가요?
재료입력 화면

## 화면
![스크린샷 2021-12-08 오전 3 42 10](https://user-images.githubusercontent.com/55980680/145087923-d20e41e4-f95e-460d-9fae-214fa976dd1c.png)
![스크린샷 2021-12-08 오전 3 42 36](https://user-images.githubusercontent.com/55980680/145087919-3d348a3d-5067-4f5d-bcc6-e072bc198887.png)

## 구체적인 작업 내용
- 재료 1개 이상 입력시 확인&삭제 버튼 활성화
- 입력 최대 10개까지
- 확인 버튼 클릭시 데이터 전달
- 재료 입력 삭제모드로 진입 -> 아이템 선택 -> 삭제

## 기타
삭제할 재료를 클릭했을 때 item의 `background`와 `textColor`가 바뀌어야 해서 
`selector`를 만들어서 적용시켰는데 아무리해도 적용이 안돼요🥲
우선 TODO로 빼놨고 추후 수정해서 올리겠습니다

## Close Issue
closes #35

2021-12-08 16:08 UTC, junieberry requested changes

2021-12-08 16:08 UTC, junieberry commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
> +    private val write2ViewModel: Write2ViewModel by viewModels()
아직 레시피 작성 부분이 안 나오긴 했는데 프래그먼트 모두가 하나의 뷰모델을 공유해야할 것 같아요! viewModelOwner을 activity가 갖고 프래그먼트들이 공유하는 그런 방식... swagger에 있는 api랑 크게 다르지 않을 것 같아서 한번 보셔도 좋을 것 같아요!

2021-12-09 11:39 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/adapter/WriteTagAdapter.kt
> +                itemClickListener(tagItem)}
```suggestion
            binding.root.setOnClickListener { itemClickListener(tagItem) }
```

2021-12-09 12:53 UTC, jionchu reviewed
수고하셨습니다~😊

2021-12-09 12:53 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
> +        binding.write2ViewModel = write2ViewModel
다른 변수들이랑 동일하게 `writeSecondViewModel`로 하면 좋을 것 같아용
```suggestion
        binding.writeSecondViewModel = writeSecondViewModel
```

2021-12-09 12:53 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/Write2ViewModel.kt
> +        get() = _minusListLiveData
굳이 `LiveData`를 변수에 붙일 필요는 없을 것 같아용 `addTagList`나 `addTags`는 어떨까요?

2021-12-09 12:53 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +    fun cancleInput() {
```suggestion
    fun cancelInput() {
```
근데 이거 어디에서 쓰이는 함수인가요?? 굳이 함수로 정의하지 않고 필요한 곳에서 바로 `finish()`로 처리해도 될 것 같아용

2021-12-09 12:53 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +    fun removeClickListener() {
함수명이 clickListener를 제거하는 기능으로 느껴져서 다른 이름으로 수정하는 게 어떨까 싶어요!

2021-12-09 12:53 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +                binding.writeTagTvRemove.setTextColor(resources.getColor(R.color.main_orange))
변수 이름들을 `remove`와 `delete` 중 하나로 통일하는 건 어떨까요?

2021-12-09 14:06 UTC, ashwon12 commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +    fun cancleInput() {
얘는 xml에서 취소버튼 눌렀을 때 호출하는 함수여서 따로 빼놓았습니당

2021-12-09 14:09 UTC, jionchu commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +    fun cancleInput() {
아하 데이터 관련된 부분은 아니니까 xml에서 처리하지 않고 액티비티에서 바로 `binding.button.setOnClickListener { finish() }`로 처리하는 건 어떨까요?

2021-12-09 14:12 UTC, ashwon12 commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +    fun cancleInput() {
넵 그게 좋을거 같아요! 수정하겠습니당

2021-12-09 14:18 UTC, ashwon12 commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
> +    private val write2ViewModel: Write2ViewModel by viewModels()
저도 공통으로 사용되는 데이터들이 많다고 생각했었는데 좋은 의견인거 같습니당.
이 부분은 다음 pr에서 적용시켜 보겠습니다!

2021-12-09 15:53 UTC, ashwon12 commented on app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
> +    fun removeClickListener() {
삭제 -> 선택삭제 -> 삭제 이렇게 모드 변경하는 리스너여서
`changeModeClickLinstner` ..?!

2021-12-10 01:08 UTC, jionchu approved these changes
LGTM 👍

2021-12-10 05:13 UTC, junieberry commented
LGTM!!😜

2021-12-10 05:31 UTC, merged